module Bible
  require 'hexapdf'

  class Book
    def to_pdf!(doc)
    end
  end

  class Bible
    def to_pdf
      composer = HexaPDF::Composer.new
      composer.text("""
          Public Domain Catholic Bible (Edition: #{self.edition.capitalize})
          Texts by: https://www.sacredbible.org
          PDF generated by Rdbo (https://github.com/rdbo/biblegen)
        """,
        position: [0, 0],
        text_align: :right
      )
      composer.text(
        "The Holy Bible",
        text_valign: :center,
        text_align: :center,
        font_size: 48,
        font_bold: true
      )
      composer
    end
  end
end
