module Bible
  require 'hexapdf'
  require 'date'

  class Chapter
    def to_pdf!(composer)
      composer.text(self.title + "\n\n", style: :chapter_title)
      composer.formatted_text(
        self.versicles.flat_map{|x| [{text: x[0].to_s + ". ", style: :versicle_number }, x[1], "\n"]
        }
      )
      composer.text("\n")
    end
  end

  class Book
    def to_pdf!(composer)
      composer.text(
        self.name,
        style: :book_title
      )
      self.chapters.each do |chapter|
        chapter.to_pdf!(composer)
      end
      composer.new_page
    end
  end

  class Bible
    def to_pdf
      composer = HexaPDF::Composer.new
      composer.styles(
        base: {},
        bible_title: { text_valign: :center, text_align: :center, font_size: 48, font_bold: true },
        book_title: { font_size: 18, font_bold: true, text_align: :center },
        chapter_title: { font_bold: true },
        versicle_number: { fill_color: [0.5, 0.5, 0.5] }
      )

      # Book cover
      composer.text("""
          Public Domain Catholic Bible - #{self.edition.capitalize} Edition
          Original texts found in: https://www.sacredbible.org
          Generated by Rdbo (https://github.com/rdbo/biblegen)
          PDF generation date: #{Date.today}
        """,
        position: [0, 0],
        text_align: :right
      )

      composer.text(
        "The Holy Bible",
        style: :bible_title
      )

      self.books.each do |book|
        book.to_pdf!(composer)
      end

      # Draw cross
      stamp = composer.create_stamp(100, 100) do |canvas|
        # Cross outline
        canvas.
          fill_color([0.0, 0.0, 0.0, 0.0]).
          line_width(5).
          rectangle(40, 5, 20, 90).
          fill_stroke()

        canvas.
          fill_color([0.0, 0.0, 0.0, 0.0]).
          line_width(5).
          rectangle(20, 50, 60, 20).
          fill_stroke()

        # Cross fill
        canvas.
          fill_color([0.7, 0.33, 0.08]).
          line_width(0).
          rectangle(40, 5, 20, 90).
          fill()

        canvas.
          fill_color([0.7, 0.33, 0.08]).
          line_width(0).
          rectangle(20, 50, 60, 20).
          fill()
      end

      composer.image(stamp, width: 300, height: 300, align: :center, valign: :center)

      composer
    end
  end
end
